### ISSUE TITLE
Add new lectures for Python + Data Visualization using Matplotlib

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Machine-Learning-Using-Python#5]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by hritik5102** [comment]
Hello @Bachittarjeet , I would like to work on this issue

Following thing, I would like to add in this repo 
- [x] **_Data visualization using matplotlib_** 

Thank you

**Comment by Bachittarjeet** [comment]
> Hello @Bachittarjeet , I would like to work on this issue
> 
> Following thing, I would like to add in this repo
> 
> * [x]  **_Data visualization using matplotlib_**
> 
> Thank you

Sure! Please raise Pull Request after contributing. Thanks

**Comment by hritik5102** [comment]
Hello @Bachittarjeet , Check out PR #10 

Thank you :)

**Comment by Bachittarjeet** [comment]
Done. Thanks
