### ISSUE TITLE
Add New Lecture - Data Structures using Python

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Machine-Learning-Using-Python#8]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by mhaider97** [comment]
@Bachittarjeet I have made one PR for LinkedList Data Structure. Could you please let me know if there is any change? If not please proceed with the merge.

**Comment by Bachittarjeet** [comment]
Thank you for your support. :)
